# Generated by Django 5.1.5 on 2025-02-23 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciption',
            new_name='Subscription',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subsciption',
            new_name='subscription',
        ),
    ]
