# Generated by Django 5.1.5 on 2025-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_subsciption_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='desktop_quantity',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
