# Generated by Django 5.1.5 on 2025-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subscription_desktop_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='desktop_quantity',
        ),
        migrations.AddField(
            model_name='subscription',
            name='desktopQuantity',
            field=models.IntegerField(null=True),
        ),
    ]
